---
# https://taskfile.dev
version: '3'

tasks:
  default:
    deps:
      - deps

  update-git-submodules:
    desc: Updates the Git Submodules used.
    cmds:
      - git submodule update --remote --merge

  deps:
    desc: Pull all requirements for Flatpak Builder to build the Flatpak.
    cmds:
      - git submodule init
      - git submodule update
      - flatpak --user install org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08 --assumeyes
...